### ISSUE TITLE
Tarefas Curso do Youtube (NodeStudio)

### ISSUE THREAD

**Issue by elvissouza** [elvissouza/studyofNodeSTUDIO#1]
**Criando Sites Profissionais [Curso Completo]**

---

- [x] BOAS VINDAS #1

- [x] FERRAMENTAS #2 

- [x] PREPARANDO PROJETO #3

- [x] DESIGNING IN THE BROWSER #4 

- [x] INICIANDO #5 

- [x] CDNs #6 

- [x] SOBRE O PROJETO #7 

- [x] HOME #8

- [x] NAVBAR #9 

- [x] SOBRE #10

- [x] CONTAINER, BANNER #11

- [x] SERVIÇOS #12 

- [x] MODAL E HORÁRIOS #13

- [x] UNIDADES #14 

- [x] BOTÕES HOME, ÍCONES #15 

- [x] CONTATO #16 

- [x] FOOTER #17

- [x] DOMÍNIO #18

- [x] HOSPEDAGEM #19

- [x] ENVIANDO EMAILS COM PHP #20

- [x] SOCIAL META TAGS #21

- [x] CONFIGURANDO OUTLOOK #22

- [x] ANALYTICS #23
---
- [x] **Projeto Finalizado**
